import type {
  CompileModule,
  FitnessFunction,
  ThreeLayerMap,
  ProcessorSpec,
  GrowthProgram,
  Species,
  InterferenceCell,
} from '@/types/compile';

// ---------------------------------------------------------------------------
// Fallback data embedded from experiment results.
// The frontend works without a running backend by using these constants.
// ---------------------------------------------------------------------------

export const FALLBACK_MODULES: CompileModule[] = [
  { id: 0, role: 'core', n_neurons: 2480, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 1, role: 'core', n_neurons: 2736, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 2, role: 'intermediary', n_neurons: 5823, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 3, role: 'core', n_neurons: 4964, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 4, role: 'core', n_neurons: 860, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 5, role: 'core', n_neurons: 1920, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 6, role: 'intermediary', n_neurons: 5012, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 7, role: 'source', n_neurons: 4117, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 8, role: 'core', n_neurons: 2268, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 9, role: 'intermediary', n_neurons: 6182, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 10, role: 'intermediary', n_neurons: 5441, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 11, role: 'sink', n_neurons: 2231, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 12, role: 'core', n_neurons: 1250, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 13, role: 'core', n_neurons: 1764, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 14, role: 'sink', n_neurons: 2700, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 15, role: 'core', n_neurons: 1448, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 16, role: 'source', n_neurons: 2607, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 17, role: 'intermediary', n_neurons: 2353, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 18, role: 'intermediary', n_neurons: 3423, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 19, role: 'intermediary', n_neurons: 1572, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 20, role: 'core', n_neurons: 798, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 21, role: 'core', n_neurons: 589, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 22, role: 'sink', n_neurons: 4856, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 23, role: 'intermediary', n_neurons: 3225, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 24, role: 'core', n_neurons: 5015, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 25, role: 'source', n_neurons: 3899, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 26, role: 'core', n_neurons: 3023, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 27, role: 'source', n_neurons: 2554, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 28, role: 'sink', n_neurons: 3900, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 29, role: 'core', n_neurons: 1268, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 30, role: 'intermediary', n_neurons: 2306, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 31, role: 'core', n_neurons: 1410, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 32, role: 'intermediary', n_neurons: 3212, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 33, role: 'intermediary', n_neurons: 2105, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 34, role: 'source', n_neurons: 3613, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 35, role: 'core', n_neurons: 1728, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 36, role: 'core', n_neurons: 1364, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 37, role: 'core', n_neurons: 673, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 38, role: 'core', n_neurons: 1381, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 39, role: 'core', n_neurons: 1335, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 40, role: 'sink', n_neurons: 3000, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 41, role: 'intermediary', n_neurons: 4523, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 42, role: 'source', n_neurons: 5807, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 43, role: 'core', n_neurons: 1461, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 44, role: 'core', n_neurons: 1246, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 45, role: 'intermediary', n_neurons: 4511, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 46, role: 'core', n_neurons: 4168, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 47, role: 'core', n_neurons: 738, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 48, role: 'source', n_neurons: 2687, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
  { id: 49, role: 'core', n_neurons: 781, top_super_class: 'optic', top_nt: 'ACH', top_group: 'ME' },
];

export const FALLBACK_FITNESS_FUNCTIONS: FitnessFunction[] = [
  {
    name: 'arousal',
    seeds: [
      { seed: 123, baseline_fitness: 10, final_fitness: 16, improvement: 6, total_accepted: 4, total_mutations: 250 },
      { seed: 42, baseline_fitness: 14, final_fitness: 16, improvement: 2, total_accepted: 2, total_mutations: 250 },
      { seed: 777, baseline_fitness: 15, final_fitness: 17, improvement: 2, total_accepted: 2, total_mutations: 250 },
    ],
    evolvable_pairs: [
      { pair: '45->36', pre_module: 45, post_module: 36, n_synapses: 1418, best_delta: 3.0, best_scale: 0.9125 },
      { pair: '12->26', pre_module: 12, post_module: 26, n_synapses: 458, best_delta: 1.0, best_scale: 2.2417 },
      { pair: '1->5', pre_module: 1, post_module: 5, n_synapses: 16, best_delta: 1.0, best_scale: 1.2659 },
      { pair: '41->5', pre_module: 41, post_module: 5, n_synapses: 109, best_delta: 1.0, best_scale: 0.515 },
      { pair: '1->39', pre_module: 1, post_module: 39, n_synapses: 196, best_delta: 1.0, best_scale: 1.9672 },
      { pair: '40->16', pre_module: 40, post_module: 16, n_synapses: 8143, best_delta: 1.0, best_scale: 0.5971 },
      { pair: '41->7', pre_module: 41, post_module: 7, n_synapses: 21033, best_delta: 1.0, best_scale: 0.9019 },
      { pair: '10->14', pre_module: 10, post_module: 14, n_synapses: 2461, best_delta: 1.0, best_scale: 1.3972 },
    ],
    all_mutations: [],
  },
  {
    name: 'efficiency',
    seeds: [
      { seed: 777, baseline_fitness: 0, final_fitness: 0, improvement: 0, total_accepted: 0, total_mutations: 250 },
    ],
    evolvable_pairs: [],
    all_mutations: [],
  },
  {
    name: 'escape',
    seeds: [
      { seed: 123, baseline_fitness: 35, final_fitness: 37, improvement: 2, total_accepted: 2, total_mutations: 250 },
      { seed: 42, baseline_fitness: 22, final_fitness: 22, improvement: 0, total_accepted: 0, total_mutations: 2 },
      { seed: 777, baseline_fitness: 34, final_fitness: 37, improvement: 3, total_accepted: 3, total_mutations: 250 },
    ],
    evolvable_pairs: [
      { pair: '49->25', pre_module: 49, post_module: 25, n_synapses: 275, best_delta: 1.0, best_scale: 2.9846 },
      { pair: '39->30', pre_module: 39, post_module: 30, n_synapses: 174, best_delta: 1.0, best_scale: 1.2144 },
      { pair: '21->49', pre_module: 21, post_module: 49, n_synapses: 5, best_delta: 1.0, best_scale: 1.0269 },
      { pair: '39->11', pre_module: 39, post_module: 11, n_synapses: 84, best_delta: 1.0, best_scale: 1.0844 },
      { pair: '46->30', pre_module: 46, post_module: 30, n_synapses: 40717, best_delta: 1.0, best_scale: 2.4782 },
    ],
    all_mutations: [],
  },
  {
    name: 'inhibition',
    seeds: [
      { seed: 777, baseline_fitness: -6, final_fitness: -6, improvement: 0, total_accepted: 0, total_mutations: 250 },
    ],
    evolvable_pairs: [],
    all_mutations: [],
  },
  {
    name: 'navigation',
    seeds: [
      { seed: 123, baseline_fitness: 3.0, final_fitness: 6.0, improvement: 3.0, total_accepted: 4, total_mutations: 250 },
      { seed: 42, baseline_fitness: 4.5, final_fitness: 6.0, improvement: 1.5, total_accepted: 3, total_mutations: 250 },
      { seed: 777, baseline_fitness: 5.5, final_fitness: 6.5, improvement: 1.0, total_accepted: 2, total_mutations: 250 },
    ],
    evolvable_pairs: [
      { pair: '45->36', pre_module: 45, post_module: 36, n_synapses: 1418, best_delta: 1.5, best_scale: 0.9125 },
      { pair: '12->26', pre_module: 12, post_module: 26, n_synapses: 458, best_delta: 0.5, best_scale: 2.2417 },
      { pair: '1->5', pre_module: 1, post_module: 5, n_synapses: 16, best_delta: 0.5, best_scale: 1.2659 },
      { pair: '41->5', pre_module: 41, post_module: 5, n_synapses: 109, best_delta: 0.5, best_scale: 0.515 },
      { pair: '28->3', pre_module: 28, post_module: 3, n_synapses: 14980, best_delta: 0.5, best_scale: 0.7953 },
      { pair: '1->39', pre_module: 1, post_module: 39, n_synapses: 196, best_delta: 0.5, best_scale: 1.9672 },
      { pair: '40->16', pre_module: 40, post_module: 16, n_synapses: 8143, best_delta: 0.5, best_scale: 0.5971 },
      { pair: '41->7', pre_module: 41, post_module: 7, n_synapses: 21033, best_delta: 0.5, best_scale: 0.9019 },
      { pair: '10->14', pre_module: 10, post_module: 14, n_synapses: 2461, best_delta: 0.5, best_scale: 1.3972 },
    ],
    all_mutations: [],
  },
  {
    name: 'turning',
    seeds: [
      { seed: 123, baseline_fitness: 4.4, final_fitness: 5.5, improvement: 1.1, total_accepted: 1, total_mutations: 250 },
      { seed: 42, baseline_fitness: 4.4, final_fitness: 5.5, improvement: 1.1, total_accepted: 1, total_mutations: 250 },
      { seed: 777, baseline_fitness: 2.2, final_fitness: 6.6, improvement: 4.4, total_accepted: 3, total_mutations: 250 },
    ],
    evolvable_pairs: [
      { pair: '3->19', pre_module: 3, post_module: 19, n_synapses: 15824, best_delta: 1.1, best_scale: 0.5941 },
      { pair: '17->9', pre_module: 17, post_module: 9, n_synapses: 34001, best_delta: 1.1, best_scale: 0.3686 },
      { pair: '35->27', pre_module: 35, post_module: 27, n_synapses: 503, best_delta: 2.2, best_scale: 2.0454 },
      { pair: '21->13', pre_module: 21, post_module: 13, n_synapses: 4, best_delta: 1.1, best_scale: 2.5142 },
      { pair: '17->32', pre_module: 17, post_module: 32, n_synapses: 60648, best_delta: 1.1, best_scale: 2.0809 },
    ],
    all_mutations: [],
  },
  {
    name: 'circles',
    seeds: [
      { seed: 123, baseline_fitness: 2.1, final_fitness: 3.9, improvement: 1.8, total_accepted: 4, total_mutations: 250 },
      { seed: 42, baseline_fitness: 1.8, final_fitness: 3.4, improvement: 1.6, total_accepted: 3, total_mutations: 250 },
    ],
    evolvable_pairs: [
      { pair: '14->26', pre_module: 14, post_module: 26, n_synapses: 5920, best_delta: 0.8, best_scale: 1.39 },
      { pair: '19->27', pre_module: 19, post_module: 27, n_synapses: 1409, best_delta: 0.5, best_scale: 3.49 },
      { pair: '21->45', pre_module: 21, post_module: 45, n_synapses: 853, best_delta: 0.3, best_scale: 2.27 },
      { pair: '12->26', pre_module: 12, post_module: 26, n_synapses: 458, best_delta: 0.2, best_scale: 3.65 },
    ],
    all_mutations: [],
  },
  {
    name: 'rhythm',
    seeds: [
      { seed: 123, baseline_fitness: 1.5, final_fitness: 2.8, improvement: 1.3, total_accepted: 5, total_mutations: 250 },
      { seed: 42, baseline_fitness: 1.2, final_fitness: 2.5, improvement: 1.3, total_accepted: 4, total_mutations: 250 },
    ],
    evolvable_pairs: [
      { pair: '45->36', pre_module: 45, post_module: 36, n_synapses: 1418, best_delta: 0.4, best_scale: 1.29 },
      { pair: '12->26', pre_module: 12, post_module: 26, n_synapses: 458, best_delta: 0.3, best_scale: 3.65 },
      { pair: '19->27', pre_module: 19, post_module: 27, n_synapses: 1409, best_delta: 0.3, best_scale: 3.49 },
      { pair: '45->47', pre_module: 45, post_module: 47, n_synapses: 312, best_delta: 0.2, best_scale: 1.37 },
      { pair: '27->45', pre_module: 27, post_module: 45, n_synapses: 967, best_delta: 0.1, best_scale: 1.70 },
    ],
    all_mutations: [],
  },
];

export const FALLBACK_THREE_LAYER_MAP: ThreeLayerMap = {
  os_layer: [
    { src: 1, tgt: 5, functions: ['arousal', 'navigation'] },
    { src: 1, tgt: 39, functions: ['arousal', 'navigation'] },
    { src: 10, tgt: 14, functions: ['arousal', 'navigation'] },
    { src: 12, tgt: 26, functions: ['arousal', 'navigation', 'circles', 'rhythm'] },
    { src: 40, tgt: 16, functions: ['arousal', 'navigation'] },
    { src: 41, tgt: 5, functions: ['arousal', 'navigation'] },
    { src: 41, tgt: 7, functions: ['arousal', 'navigation'] },
    { src: 45, tgt: 36, functions: ['arousal', 'navigation', 'rhythm'] },
    { src: 19, tgt: 27, functions: ['circles', 'rhythm'] },
  ],
  app_layer: {
    arousal: [],
    efficiency: [],
    escape: [
      { src: 21, tgt: 49 },
      { src: 39, tgt: 11 },
      { src: 39, tgt: 30 },
      { src: 46, tgt: 30 },
      { src: 49, tgt: 25 },
    ],
    inhibition: [],
    navigation: [
      { src: 28, tgt: 3 },
    ],
    turning: [
      { src: 3, tgt: 19 },
      { src: 17, tgt: 9 },
      { src: 17, tgt: 32 },
      { src: 21, tgt: 13 },
      { src: 35, tgt: 27 },
    ],
    circles: [
      { src: 14, tgt: 26 },
      { src: 21, tgt: 45 },
    ],
    rhythm: [
      { src: 45, tgt: 47 },
      { src: 27, tgt: 45 },
    ],
  },
  hardware_stats: {
    total_pairs: 2500,
    tested_pairs: 641,
    evolvable_pairs: 24,
    frozen_pairs: 622,
    frozen_pct: 97.0,
    irrelevant_pairs: 1859,
    irrelevant_pct: 74.4,
  },
};

export const FALLBACK_PROCESSORS: ProcessorSpec[] = [
  {
    id: 'gene-guided-v1',
    name: 'Gene-Guided Processor',
    method: 'gene-guided',
    n_neurons: 8158,
    n_synapses: 686973,
    essential_modules: [4, 19],
    hemilineages: [
      'VPNd2', 'VLPp2', 'DM3_CX_d2', 'LB23', 'LB12', 'VLPl2_medial',
      'LB7', 'VLPl&p2_posterior', 'MD3', 'MX12', 'VLPl&p2_lateral',
      'DM1_CX_d2', 'WEDd1', 'MX3', 'VPNd1', 'putative_primary',
      'CREa2_medial', 'CREa1_dorsal', 'SLPal3_and_SLPal4_dorsal',
    ],
    behaviors_compiled: ['navigation', 'escape', 'arousal', 'circles', 'rhythm'],
    behaviors_failed: ['turning'],
    interference_matrix: [
      { compiled_for: 'navigation', tested_on: 'navigation', delta_pct: 34, score: 1219, baseline: 891 },
      { compiled_for: 'navigation', tested_on: 'escape', delta_pct: 26, score: 161, baseline: 128 },
      { compiled_for: 'navigation', tested_on: 'arousal', delta_pct: 33, score: 1882, baseline: 1415 },
      { compiled_for: 'navigation', tested_on: 'circles', delta_pct: 22, score: 206, baseline: 169 },
      { compiled_for: 'escape', tested_on: 'navigation', delta_pct: -9, score: 811, baseline: 891 },
      { compiled_for: 'escape', tested_on: 'escape', delta_pct: 234, score: 428, baseline: 128 },
      { compiled_for: 'escape', tested_on: 'arousal', delta_pct: 123, score: 3155, baseline: 1415 },
      { compiled_for: 'escape', tested_on: 'circles', delta_pct: 44, score: 243, baseline: 169 },
      { compiled_for: 'arousal', tested_on: 'navigation', delta_pct: 39, score: 1238, baseline: 891 },
      { compiled_for: 'arousal', tested_on: 'escape', delta_pct: 33, score: 170, baseline: 128 },
      { compiled_for: 'arousal', tested_on: 'arousal', delta_pct: 40, score: 1981, baseline: 1415 },
      { compiled_for: 'arousal', tested_on: 'circles', delta_pct: 61, score: 272, baseline: 169 },
      { compiled_for: 'circles', tested_on: 'navigation', delta_pct: 35, score: 1203, baseline: 891 },
      { compiled_for: 'circles', tested_on: 'escape', delta_pct: -41, score: 76, baseline: 128 },
      { compiled_for: 'circles', tested_on: 'arousal', delta_pct: 22, score: 1726, baseline: 1415 },
      { compiled_for: 'circles', tested_on: 'circles', delta_pct: 42, score: 240, baseline: 169 },
    ],
    compatible_pairs: [
      ['navigation', 'escape'], ['navigation', 'arousal'], ['navigation', 'circles'],
      ['escape', 'arousal'], ['arousal', 'circles'],
    ],
    conflicting_pairs: [
      ['circles', 'escape'],
    ],
  },
  {
    id: 'module-selected-v1',
    name: 'Module-Selected Processor',
    method: 'module',
    n_neurons: 20626,
    n_synapses: 374344,
    essential_modules: [4, 19],
    behaviors_compiled: ['navigation', 'escape', 'arousal', 'circles', 'rhythm'],
    behaviors_failed: ['turning'],
  },
];

export const FALLBACK_GROWTH_PROGRAMS: GrowthProgram[] = [
  {
    id: 'growth-v1',
    processor_id: 'gene-guided-v1',
    n_cell_types: 19,
    n_connection_rules: 30,
    cell_types: [
      { hemilineage: 'putative_primary', count: 3875, proportion: 0.4793, neurotransmitter: 'acetylcholine', spatial_centroid: [140000, 60000, 3000] },
      { hemilineage: 'VPNd2', count: 815, proportion: 0.1008, neurotransmitter: 'acetylcholine', spatial_centroid: [120000, 50000, 2500] },
      { hemilineage: 'VPNd1', count: 594, proportion: 0.0735, neurotransmitter: 'acetylcholine', spatial_centroid: [125000, 55000, 2800] },
      { hemilineage: 'VLPl2_medial', count: 316, proportion: 0.0391, neurotransmitter: 'acetylcholine', spatial_centroid: [135000, 48000, 3200] },
      { hemilineage: 'MX3', count: 249, proportion: 0.0308, neurotransmitter: 'acetylcholine', spatial_centroid: [110000, 65000, 2000] },
      { hemilineage: 'WEDd1', count: 196, proportion: 0.0242, neurotransmitter: 'acetylcholine', spatial_centroid: [145000, 52000, 2600] },
      { hemilineage: 'DM3_CX_d2', count: 180, proportion: 0.0223, neurotransmitter: 'acetylcholine', spatial_centroid: [130000, 58000, 3500] },
      { hemilineage: 'DM1_CX_d2', count: 165, proportion: 0.0204, neurotransmitter: 'acetylcholine', spatial_centroid: [128000, 56000, 3400] },
      { hemilineage: 'LB23', count: 150, proportion: 0.0186, neurotransmitter: 'gaba', spatial_centroid: [115000, 62000, 2200] },
      { hemilineage: 'LB12', count: 140, proportion: 0.0173, neurotransmitter: 'acetylcholine', spatial_centroid: [118000, 60000, 2400] },
      { hemilineage: 'LB7', count: 130, proportion: 0.0161, neurotransmitter: 'acetylcholine', spatial_centroid: [116000, 61000, 2300] },
      { hemilineage: 'MX12', count: 120, proportion: 0.0148, neurotransmitter: 'acetylcholine', spatial_centroid: [112000, 64000, 2100] },
      { hemilineage: 'VLPl&p2_posterior', count: 110, proportion: 0.0136, neurotransmitter: 'acetylcholine', spatial_centroid: [138000, 46000, 3100] },
      { hemilineage: 'VLPl&p2_lateral', count: 100, proportion: 0.0124, neurotransmitter: 'gaba', spatial_centroid: [136000, 47000, 3000] },
      { hemilineage: 'MD3', count: 95, proportion: 0.0118, neurotransmitter: 'acetylcholine', spatial_centroid: [108000, 66000, 1900] },
      { hemilineage: 'VLPp2', count: 90, proportion: 0.0111, neurotransmitter: 'dopamine', spatial_centroid: [137000, 49000, 3100] },
      { hemilineage: 'CREa2_medial', count: 85, proportion: 0.0105, neurotransmitter: 'acetylcholine', spatial_centroid: [132000, 57000, 3300] },
      { hemilineage: 'CREa1_dorsal', count: 80, proportion: 0.0099, neurotransmitter: 'dopamine', spatial_centroid: [131000, 56000, 3200] },
      { hemilineage: 'SLPal3_and_SLPal4_dorsal', count: 75, proportion: 0.0093, neurotransmitter: 'acetylcholine', spatial_centroid: [142000, 54000, 2900] },
    ],
    connection_rules: [
      { from_hemilineage: 'putative_primary', to_hemilineage: 'VPNd2', synapse_count: 45000, connection_probability: 0.0142, average_weight: 1.85 },
      { from_hemilineage: 'putative_primary', to_hemilineage: 'VPNd1', synapse_count: 38000, connection_probability: 0.0165, average_weight: 1.72 },
      { from_hemilineage: 'putative_primary', to_hemilineage: 'MX3', synapse_count: 22000, connection_probability: 0.0228, average_weight: 1.45 },
      { from_hemilineage: 'VPNd2', to_hemilineage: 'putative_primary', synapse_count: 35000, connection_probability: 0.0111, average_weight: 1.63 },
      { from_hemilineage: 'VPNd2', to_hemilineage: 'VLPl2_medial', synapse_count: 12000, connection_probability: 0.0466, average_weight: 1.31 },
      { from_hemilineage: 'VPNd1', to_hemilineage: 'putative_primary', synapse_count: 28000, connection_probability: 0.0122, average_weight: 1.58 },
      { from_hemilineage: 'VPNd1', to_hemilineage: 'WEDd1', synapse_count: 8500, connection_probability: 0.0730, average_weight: 1.22 },
      { from_hemilineage: 'MX3', to_hemilineage: 'putative_primary', synapse_count: 15000, connection_probability: 0.0156, average_weight: 1.41 },
      { from_hemilineage: 'MX3', to_hemilineage: 'VPNd2', synapse_count: 9000, connection_probability: 0.0443, average_weight: 1.15 },
      { from_hemilineage: 'WEDd1', to_hemilineage: 'DM3_CX_d2', synapse_count: 6500, connection_probability: 0.1013, average_weight: 1.08 },
      { from_hemilineage: 'VLPl2_medial', to_hemilineage: 'VPNd2', synapse_count: 7800, connection_probability: 0.0303, average_weight: 1.19 },
      { from_hemilineage: 'DM3_CX_d2', to_hemilineage: 'DM1_CX_d2', synapse_count: 5200, connection_probability: 0.0830, average_weight: 0.95 },
      { from_hemilineage: 'DM1_CX_d2', to_hemilineage: 'putative_primary', synapse_count: 11000, connection_probability: 0.0172, average_weight: 1.35 },
      { from_hemilineage: 'LB23', to_hemilineage: 'putative_primary', synapse_count: 8000, connection_probability: 0.0138, average_weight: -1.20 },
      { from_hemilineage: 'LB12', to_hemilineage: 'VPNd2', synapse_count: 5500, connection_probability: 0.0481, average_weight: 1.05 },
      { from_hemilineage: 'LB7', to_hemilineage: 'VPNd1', synapse_count: 4800, connection_probability: 0.0587, average_weight: 0.98 },
      { from_hemilineage: 'MX12', to_hemilineage: 'MX3', synapse_count: 4200, connection_probability: 0.1407, average_weight: 0.92 },
      { from_hemilineage: 'VLPl&p2_posterior', to_hemilineage: 'VLPl2_medial', synapse_count: 3800, connection_probability: 0.1094, average_weight: 0.88 },
      { from_hemilineage: 'VLPl&p2_lateral', to_hemilineage: 'putative_primary', synapse_count: 6000, connection_probability: 0.0155, average_weight: -0.85 },
      { from_hemilineage: 'MD3', to_hemilineage: 'WEDd1', synapse_count: 3500, connection_probability: 0.1884, average_weight: 0.82 },
      { from_hemilineage: 'VLPp2', to_hemilineage: 'VPNd2', synapse_count: 3200, connection_probability: 0.0441, average_weight: 0.78 },
      { from_hemilineage: 'CREa2_medial', to_hemilineage: 'DM3_CX_d2', synapse_count: 2800, connection_probability: 0.1831, average_weight: 0.75 },
      { from_hemilineage: 'CREa1_dorsal', to_hemilineage: 'DM1_CX_d2', synapse_count: 2500, connection_probability: 0.1894, average_weight: 0.72 },
      { from_hemilineage: 'SLPal3_and_SLPal4_dorsal', to_hemilineage: 'putative_primary', synapse_count: 4500, connection_probability: 0.0155, average_weight: 0.68 },
      { from_hemilineage: 'putative_primary', to_hemilineage: 'DM3_CX_d2', synapse_count: 18000, connection_probability: 0.0258, average_weight: 1.55 },
      { from_hemilineage: 'putative_primary', to_hemilineage: 'DM1_CX_d2', synapse_count: 16000, connection_probability: 0.0250, average_weight: 1.48 },
      { from_hemilineage: 'putative_primary', to_hemilineage: 'LB23', synapse_count: 9500, connection_probability: 0.0164, average_weight: 1.32 },
      { from_hemilineage: 'putative_primary', to_hemilineage: 'WEDd1', synapse_count: 12000, connection_probability: 0.0158, average_weight: 1.38 },
      { from_hemilineage: 'VPNd2', to_hemilineage: 'VPNd1', synapse_count: 8000, connection_probability: 0.0165, average_weight: 1.25 },
      { from_hemilineage: 'VPNd1', to_hemilineage: 'VPNd2', synapse_count: 7500, connection_probability: 0.0155, average_weight: 1.22 },
    ],
  },
];

export const FALLBACK_SPECIES: Species[] = [
  { id: 'fly', name: 'Drosophila melanogaster', n_neurons: 139255, n_synapses: '15M', dataset: 'FlyWire FAFB v783', status: 'complete' },
  { id: 'mouse', name: 'Mus musculus (V1)', n_neurons: 70000, n_synapses: '500M', dataset: 'MICrONS minnie65', status: 'in_progress' },
];
